### ISSUE TITLE
Adding a payee

### ISSUE THREAD

**Issue by Catapillr** [Catapillr/loan-application-platform#12]
## Job story

**User**: Employee

**Situation**: Once an account has been opened for the employee they will be able to set up the people they wish to pay.

**Motivation**: I want to ensure employees can easily add the people they need to pay.

**Expected outcome**: Easy and straight forward way in which employees can add the payment and contact details of childcare providers and children's activity providers.   Quick check process on behalf of employers, to ensure the payees are childcare providers i.e. Ofsted registered in England or a children's activity provider and registered as a company via companies house 

## Screenshot or other useful information

Information required to set up a Payee:

EMPLOYEE SELECTS TYPE OF PROVIDER THEY WANT TO PAY.
--
TYPE 1: REGISTERED CHILDCARE PROVIDER. ASK FOR OFSTED OR EQUIV REGISTRATION NUMBER IF KNOWN.
TYPE 1 DETAILS:  PRE-POPULATE DETAILS BASED ON REG NUMBER, OTHERWISE USER TO SEARCH UNDER NAME FOR PROVIDER USING OFSTED DATA - CAN'T FIND THEN ADD: NAME OF PROVIDER / ADDRESS / EMAIL / TELEPHONE / KEY CONTACT NAME / BANK ACCOUNT & SORT CODE.
TYPE 2: UNREGISTERED CHILDREN'S ACTIVITY COMPANIES / ORGANISATIONS / CLUBS / CHARITIES.
TYPE 2 DETAILS: SEARCH BY NAME FOR PROVIDER IN OUR OWN DATABASE. CAN'T FIND - ADD DETAILS. NAME OF PROVIDER / ADDRESS / EMAIL / TELEPHONE / KEY CONTACT NAME / BANK ACCOUNT & SORT CODE.
MESSAGE DETAILS SAVED - NOTIFICATION ONCE PAYEE SET UP AND READY TO USE. INITIAL 24/48 HOUR TURN AROUND.
ADD IN CHILDCARE PROVIDER ACCOUNT & KIDS NAME

**Comment by PHILCATAPILLR** [comment]
Include a tax-free childcare account as a payee.

The details to be provided by the employee would be account number and sort code.  Need a simple way to check that this is an account provided by NS&I, a simple bank account verification check could do this.  I'm checking in to it.
