### ISSUE TITLE
Discovering and time-estimating our stack

### ISSUE THREAD

**Issue by maxgerber** [Catapillr/loan-application-platform#16]
We need to do a couple of **technical spikes** so that we are able to choose the best technologies for this project, and understand enough about them in order to be able to time estimate them effectively.

## Ivan
- [x] What **CMS** should we be using (if any)? (Current suggestion: **Sanity CMS**)
- [x] What are the best resources with which to explore Typescript basics?
- [x] How do we ensure an appropriately functional backend within Express.js?
- [x] What ORM should we use? (Current suggestion: **Prisma**)
- [x] What front-end / SSR react framework should we use? (Current suggestion: **Neutrino vs Next.JS**)

## Max
- [x] What **email verification technology** should we use? (Current suggestion: **Mailgun**)
- [x] What **PDF Creation** package should we use? (Current suggestion: **docxtemplater**)
- [x] What is the process/flow for using Docusign or similar? (Current suggestion: **HelloSign API**)

## General questions
- [x] How can we begin to implement testing of crucial functionality from the outset?

**Comment by ivanmauricio** [comment]
@maxgerber Here's what I've found out so far -

**CMS**: I think we should go with Sanity. As I understand it we are looking for a quick MVP solution for an admin interface. I think Sanity meets all our needs and we can reassess if we need anything more customisable when/if we expand out the employer interface.

**Typescript & Express & React framework**:  I've put these together as I think we should go with `next`. It comes with `typescript` integration comes out of the box, both for the front-end and for the server. In fact we might not even need a server, as there is a new `API routes` feature. More info [here](https://nextjs.org/blog/next-9#api-routes).

I'm still investigating `ORM` options. Will update!
