### ISSUE TITLE
Remove google login option

### ISSUE THREAD

**Issue by Catapillr** [Catapillr/loan-application-platform#180]
**Describe the bug**

Remove the Google option from the app autho login page

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to app.catapillr.com
2. Click on login
3. Scroll down to

**Expected behavior**

Remove the google login option from login screen so that the employee can only login in with the email they would have used for the application, which would contain the domains set up in the employer database.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by lucymk** [comment]
Closing as this is done
