### ISSUE TITLE
Set date range

### ISSUE THREAD

**Issue by Catapillr** [Catapillr/loan-application-platform#184]
please can you set the day to a maximum of 31, month to 12 and year to current.

![Screen Shot 2019-10-28 at 13 23 54](https://user-images.githubusercontent.com/54115279/67681986-4defb600-f986-11e9-9209-fd0e515315cf.png)

**Comment by lucymk** [comment]
@PHILCATAPILLR we followed [gov.uk best design practices](https://design-system.service.gov.uk/components/date-input/) when building this - they don't recommend limiting the user input, instead they suggest validating it and providing useful error messages which is what we have tried to do. We would not consider this a bug. If you feel strongly about it we can investigate it as a new feature.

**Comment by Catapillr** [comment]
don't consider it a bug then, I just want the copy updating.

**Comment by lucymk** [comment]
@PHILCATAPILLR can you clarify what copy you mean? Do you mean you would like the copy of the error message to be different?

**Comment by Catapillr** [comment]
apologies, I was getting confused with the other open discussion we were having.  It's not a bug in some sense because it does work, however, I'm not happy with how it is currently performing, hence it needs to be changed.  Every app I have ever used always limits the input in a date field to 2 digits, same for month and year field to either 2 or 4 digits.  Without this it just looks and feels incomplete, hence why flagged up as a bug and feature that needs to be changed.

**Comment by Catapillr** [comment]
the change I've requested to limit the number for day and month is pretty standard, without it just looks and feels very basic.

**Comment by maxgerber** [comment]
Hi @Catapillr — gotcha. We thought you meant that you wanted us to change the content of the error message in the screenshot.

It sounds like what you're asking for is already included in https://github.com/Catapillr/loan-application-platform/issues/183 ? We agree with you about restricting length and characters, so we've added a bug label to that issue.

**Comment by Catapillr** [comment]
it is different to 183, although that is date related.  In the day column, currently any number can be put into the field and i would like it to be limited to 31.  For the month, I would like the input to be limited to 12 and then the year, this should just be the current year or older, I don't think a user should be able to put a nonsense value in like 2100, for the year, it just doesn't look right to me, hope that's now clear.
