### ISSUE TITLE
signing in link

### ISSUE THREAD

**Issue by Catapillr** [Catapillr/loan-application-platform#186]
I put in an email for an account I had already created, error message points to signing in, it would be great if this could be made a hotlink to a signing in page.
![Screen Shot 2019-10-28 at 13 45 03](https://user-images.githubusercontent.com/54115279/67683459-585f7f00-f989-11e9-931b-d09fcab93b21.png)

**Comment by lucymk** [comment]
@PHILCATAPILLR this is a new feature which unfortunately is not as simple as just wrapping the text in a link, because of the way the error messages work. We're happy to put it into the backlog and look at it in the next piece of work if you like, let us know.

**Comment by Catapillr** [comment]
forget the text then, can a sign-in button be added below?

**Comment by Catapillr** [comment]
otherwise the text needs to be changed to please login at catapillr.com/dashboard

**Comment by lucymk** [comment]
@PHILCATAPILLR happy to change the text as you've suggested 😃

**Comment by Catapillr** [comment]
great, thanks.
