### ISSUE TITLE
UBO form completion to be made mandatory

### ISSUE THREAD

**Issue by Catapillr** [Catapillr/loan-application-platform#217]
**Describe the bug**
When a childcare provider completed the onboarding process, the UBO form needs to be completed, in addition to the documents provided.  Without a completed UBO, a childcare provider will not be set up.

Please pre-populate this form with all available info from companies house and ensure, the user knows which fields need to be completed and that the application can not be submitted until all fields have been completed.

![Screen Shot 2019-11-06 at 14 30 26](https://user-images.githubusercontent.com/54115279/68306760-0e218080-00a2-11ea-9aa4-cc6aed380010.png)

**Comment by Catapillr** [comment]
![screencapture-app-catapillr-register-as-a-provider-ck2m4tmyq003g071749c2w68t-2019-11-06-17_17_14](https://user-images.githubusercontent.com/54115279/68324768-fce76c80-00bf-11ea-8b66-a8702bb81cd9.png)

**Comment by Catapillr** [comment]
This form can't be left blank, otherwise the KYC verification fails.

**Comment by lucymk** [comment]
A note to ourselves: make sure all fields have been filled in before allowing submission, currently can submit with only DOB.
