### ISSUE TITLE
Confirmation email (after employee signing)

### ISSUE THREAD

**Issue by maxgerber** [Catapillr/loan-application-platform#34]
When employee clicks link from email, they get taken to the confirmation screen IF they have successfully signed the loan agreement. 

So on this page we need to check the agreement and render app complete if so. 
If not, should redirect to an error page.

**Comment by lucymk** [comment]
Maybe we need to put something into the DB once the user has signed (we would put this in the listen-sign-event endpoint) which we can then check for on the front end. We could be checking for it on the confirmation page -> so it would automatically move on once the employee sign event had been triggered.

**Comment by ivanmauricio** [comment]
For now we are going to change the copy on the post summary screen telling them that they need to sign the document and that they will then get an email outlining the next steps.
