### ISSUE TITLE
Integrate e-sign API

### ISSUE THREAD

**Issue by maxgerber** [Catapillr/loan-application-platform#36]
Integrating and setting up e-sign (or similar) to interact correctly with the platform

**Comment by maxgerber** [comment]
@Catapillr I've compared various e-sign platforms in [this table](https://www.notion.so/infactcoop/c78dac69955845018c59a9634656f933?v=e9824fee5a6a4a64b87b6f5d837f5015) in terms of pricing model and our developer assessments of them. Would be great to hear your thoughts!

**Comment by Catapillr** [comment]
Thanks for this Max.

I'm happy to go with HelloSign, looks like a good option and has Node SDK and a fair price.
