### ISSUE TITLE
Notes from sprint demo

### ISSUE THREAD

**Issue by lucymk** [Catapillr/loan-application-platform#63]
- [x] update date placeholder copy
- [x] add salary screen if max salary present in eligibility criteria and reflect max salary in range
- [x] update content of receipt to remove service charge (waiting on new copy)
- [x] double check if nationality is needed, remove if not
- [x] move question about permanent role to come first and update copy (waiting on new copy)
- [x] remove next button from 'Just a Note' page
- [x] update loan template (waiting on new copy)
- [x] add final form submission error
- [x] not all borders are red when validation errors show
- [x] add red border to verification code when wrong/expired code entered
- [x] connect range and number inputs 
- [x] next/previous/submit buttons should be same width not fit-content
- [x] add overflow scroll to loan summary page and make sure there's enough padding on the top of the box
- [x] check loan summary page complete
- [x] add user id from mango pay into db
- [x] change 'user' to 'employee' across the app

**Comment by lucymk** [comment]
@PHILCATAPILLR can you let me know what the new version of the 'receipt' box on the loan amount picker page should say?

**Comment by PHILCATAPILLR** [comment]
Hi,

think it just needs to be super simple, no need for text or calculation of fees.  I've therefore come up with the following.  I like the FAQ sentence to remain in place, as I think that's helpul.
 


![Screen Shot 2019-09-13 at 16 24 19](https://user-images.githubusercontent.com/55090926/64874530-1d0c2980-d643-11e9-9cd9-e60b4ae051c2.png)
